### ISSUE TITLE
Provide Windows XP security warning on startup

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit#538]
Modify OSUtils to detect Windows XP and issue a security warning on each startup. The intention is to get people off Windows XP and on to a more secure operating system, either in the Windows or Unix families.

A similar requirement is in place for MBHD.

**Comment by gary-rowe** [comment]
Code for this is present in MBHD and we should inform users that they are no longer in a secure enough environment for Bitcoin.

**Comment by jim618** [comment]
I have backported the MessageBox from MBHD and OSUtils so that the user now gets a warning if they are using XP at startup as follows:

![screen shot 2015-07-26 at 14 19 55](https://cloud.githubusercontent.com/assets/919427/8894084/d63048fe-33a1-11e5-9d9d-9bc297d5ef34.png)

Note that they can dismiss the alert and carry on - it does not shut down the client like it does with MBHD.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Removed some unnecessary code in the catch block. The dialog should trigger correctly on XP and has been tested with a VM.

Closing.
