### ISSUE TITLE
Create installer for Release 0.5.19

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit#702]
Once all Release 0.5.19 issues are out of the way the installer can be created and pushed to the main website.

This needs to be done in line with the procedure in the installer repo.

**Comment by sledz** [comment]
Is release 0.5.19 available by now?

**Comment by gary-rowe** [comment]
Not yet. We have to release [MultiBit HD 0.1.2](https://github.com/bitcoin-solutions/multibit-hd/milestones/Release%200.1.2) first and then we can consider diverting attention to 0.5.19. There's lots to do and we're a small team.

**Comment by jim618** [comment]
### Prepare
Ensure all issues are completed for milestone.
Update SPV checkpoints file. 
Update the localisation files from crowdin.com.
Merge from develop into master, tag code.
Final verification that unit tests run correctly.
Check correct copy of 'staging' directory is in installer target-classic directory. 
Create update-message.html for version check user notification.
Check install4j auto-update points to updates.xml and NOT updates-test.xml.

### Build
Create and sign installer using Windows and Apple developer keys.
Create and check PGP signatures for binaries.
Create and check SHA256 files for binaries.
Create release note with SHA256 hashs of the binaries.
Verify the release note with earlier version of MultiBit Classic.

### Smoke test
Push binaries to website multibit-classic-0.0.0
Download, install and perform manual test of functionality

### Release
Copy multibit-classic-0.0.0 binaries to correct release directory.
Push the website code to multibit.org.
Issue general notification on social media Reddit/Twitter/BitcoinTalk if not already in place. Wait 24 hours for feedback.
Push to releases/multibit-classic/updates.xml so that auto updates start.

**Comment by gary-rowe** [comment]
Verified latest 0.0.0 installers are working with the "MultiBit Classic" branding throughout (Win + OS X).

**Comment by gary-rowe** [comment]
Verified latest installers are working correctly (Win + OS X)
