### ISSUE TITLE
Test bitcoin uris work in 0.5.19

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit#718]
As we have moved to a different installer for 0.5.19 we need to check bitcoin uris work correctly

**Comment by jim618** [comment]
I have checked that bitcoin URIs work on Mac.
@gary-rowe  Can you check Win and Linux please ? (using the multibit-0.0.0 release)

PROTIP: If you have other apps registered as bitcoin URI handlers I find on a Mac you can:
1) Zip the app
2) Delete the original, leaving just the zip file.

This stops the Mac OS using that app to open the bitcoin URI and you can easily recreate the original app if you need it.

**Comment by gary-rowe** [comment]
Installed on both Linux and Windows with no problems (have previously done OS X). Some nits:

* Shortcut is named "multibit-classic" instead of "MultiBit" (installer title) or "MultiBit Classic".
* No desktop shortcut 
* No automatic registration of a Bitcoin URI
 
On Linux I could get Firefox to create a protocol handler for `bitcoin:` but Windows proved fruitless on IE, Chrome and FF. Looks like the registry is missing some detail present in the MultiBit HD installer.

Bouncing back.

**Comment by jim618** [comment]
Updated install4j installer project and pushed.

Built installers and tested on Windows 8.1 with the following results:
+ Shortcut was created on Desktop, called 'MultiBit Classic'. This worked correctly.
+ Shortcut was created in the Start view. The tile used the correct icon and was labelled 'MultiBit Classic'. THis worked correctly.
+ Auto update check is working correctly when user opens MultiBit Classic.
+ Bitcoin URI test in Chrome, MultiBit already open:  PASS
+ Bitcoin URI test in Chrome, can it open MultiBit ?:  PASS
+ Bitcoin URI test in Internet Explorer 10, MultiBit already open:  FAIL
+ Bitcoin URI test in Internet Explorer 10, can it open MultiBit ?:  FAIL

I've checked with RegEdit that the registry entry for the open command is correct.
When you click a bitcoin link it invokes the 'new version check' which you can click through - this is effectively nagware to get the user to update so is ok.

@gary-rowe  Please can you check the Linux bitcoin URI. operation.

Any ideas why the Internet Explorer 10 bitcoin URIs are not working ?
(I used the Bitcoin uri on http://gary-rowe.com by the way)

**Comment by jim618** [comment]
THis might be relevant:
http://blogs.technet.com/b/mrmlcgn/archive/2013/02/26/windows-8-associate-a-file-type-or-protocol-with-a-specific-app-using-a-gpo-e-g-default-mail-client-for-mailto-protocol.aspx

**Comment by gary-rowe** [comment]
OS X install (based on latest 0.0.0 installer):

* smooth install experience
* had to manually configure Firefox to trigger a Bitcoin URI (but this could be HD getting in the way)
* opened/closed etc all worked fine with URI clicking

Windows 64bit 8.1:

* uninstalled the previous version (all fine)
* smooth install experience with caveats
* Start Menu folder created as "MultiBit" (PASS) containing shortcut "multibit-classic" (FAIL)
* exe in C:\Program Files\MultiBit named "multibit-classic.exe" which may not correctly overwrite 0.5.18's "multibit.exe"
* clicking Bitcoin URI in FF yields "multibit-classic.exe" not "MultiBit" (could be hold over from previous install though)
* Chrome - no registration of Bitcoin URI and no response
* IE 11 - no registration of Bitcoin URI and no response

I'll hold off on the Linux installer for now since Windows needs further attention.

**Comment by gary-rowe** [comment]
It may be necessary to adjust the installer in accordance with this [SO answer](http://stackoverflow.com/a/18496435/396747)

**Comment by jim618** [comment]
After exogenous discussion Gary and I agreed to relabel everything MultiBit Classic rather than have a mixture. This includes the binary (multibit-classic.exe).

**Comment by jim618** [comment]
I have gone through the MultiBit installer and viewer.properties so that it has 'MultiBit Classic' or 'multibit-classic' instead of 'MultiBit' and 'multibit' respectively

I have created some installers and they are available at

https://multibit.org/releases/multibit-classic/multibit-classic-0.0.0/

for @gary-rowe to try out.
I expect there to be some mixups between the text 'MultiBIt Classic' and 'multibit-classic' here and there so please take care to check those.

**Comment by jim618** [comment]
I (@jim618) have tested the bitcoin URIs work on:
+ Mac. Safari. Click on agile-stack.com link and MB Classic starts up ok and fills out form. PASS. Click on link when MB Classic already started. PASS.
+ Win 8. Internet explorer. Click on agile-stack.com link and MB Classic starts up and fills out form. PASS. Click on link with MB Classic already started. PASS/

**Comment by gary-rowe** [comment]
Just tried to use the Bitcoin URI on Windows through FF. Click link, select "multibit-classic.exe", Classic opens up but then it gets weird. At first an empty dialog is shown, with only the "Remember my decision" checkbox visible - no buttons or any other controls. A bit of mousing around and the buttons appear. Click Yes, and the dialog appears a second time, this time correctly rendered.

I think this glitching is either an artefact of Swing on Windows 8 (unlikely given we're using 1.7.0_80) or a side effect of the Install4j wrapper introducing a repeatable race condition.

Given that you're not seeing it I think that my machine is either fast or flaky enough to cause the side effect. The only way to know for sure is to put it out into the field. It's not a show stopper since the user can reach a good conclusion, but it's a bit messy.

Closing (but keeping an eye on it)
