### ISSUE TITLE
lost my wallet

### ISSUE THREAD

**Issue by zikozix** [bitcoin-solutions/multibit#722]
hello all,
after i formatted my pc twice i lost my wallet, i still kow the hash " 15y86JvbXcezwyKogzqqhNT6bT1UgdT1RZ" and the password
is there any way to restor it
my kind regards

**Comment by gary-rowe** [comment]
This doesn't sound too hopeful. Just the hash (receiving address) isn't sufficient to be able to recover the wallet for security reasons. You need to recover (or find) either the wallet file or one of its backups.

Most data recovery software will only work against a single quick format, but there are some out there that are more sophisticated. Depending on how much you have in that wallet it may be easier to just buy new bitcoins.

Assuming you want to go for recovery, have a read of these help articles:

* https://multibit.org/en/help/v0.5/help_walletBackups.html
* https://multibit.org/en/help/v0.5/help_fileDescriptions.html

They will guide you to the files that you need to recover. It may be that you already have backups from an earlier time, perhaps on a USB stick. It's definitely worth hunting around old backups just in case.

I can't directly recommend any recovery software, but a Google search should turn up some good results.

Best of luck in recovering them.

Since there is nothing further that can be done here, I'll close this issue.

**Comment by Georgeh0h** [comment]
@zikozix 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
