### ISSUE TITLE
Multibit 0.5.18 Alice bcj-0.11.2-mb-alice

### ISSUE THREAD

**Issue by off-bank** [bitcoin-solutions/multibit#748]
It seems the code is not up anylonger, any idea where I can find MultiBit 0.5.18's bitcoinj fork, specifically branch bcj-0.11.2-mb-alice?
https://code.google.com/r/jimburton618-bitcoinj-coinbase-tx/source/checkout

**Comment by gary-rowe** [comment]
Oh, it's moved. You can find it here: https://github.com/bitcoin-solutions/bitcoinj-alice if you want to build it from source. Just find the appropriate branch for the version you need and do the usual `mvn clean install` locally.

We maintain a Maven repo that you can use to pull it in as a dependency using:
```
<!-- MultiBit repository for releases -->
        <repository>
            <id>mbhd-maven-release</id>
            <url>https://raw.githubusercontent.com/bitcoin-solutions/mbhd-maven/master/releases</url>
            <releases/>
        </repository>
```
See the MultiBit Classic for details.

Ideally, you shouldn't be using 0.5.18 any more since 0.5.19 is out and contains several improvements. Further MultiBit Classic is considered a legacy product and you should really migrate to MultiBit HD.

**Comment by off-bank** [comment]
Thanks! I'm trying to build SparkBit https://github.com/coinspark/sparkbit/ that is based on Multibit 0.5.18

**Comment by gary-rowe** [comment]
Well, good luck with that. The pulse is looking a bit... um... absent on that project. Are you sure you want to get involved with it?

**Comment by off-bank** [comment]
Yes, it seems blockchain is the thing now... It's a pity, it's a nice concept wallet. Flavien from coinprism is also more interested on his chain thing. 
I'm trying to install and learn from the available colored coins options, there's a lack of good wallets for assets out there.

**Comment by gary-rowe** [comment]
Yes, I think at the moment a pure-Bitcoin asset management wallet is very difficult to implement, particularly in SPV. Mixing it with Ethereum and other custom block chains is probably the way forward there.

I'll close this issue now, and wish you the best for your ongoing adventure.
