### ISSUE TITLE
Make Multibit estimate miner fees

### ISSUE THREAD

**Issue by chris-belcher** [bitcoin-solutions/multibit#759]
Lately I've seen a few people on bitcoin-related forums talk about how their transactions took a long time to confirm. I ask what wallet they use and very often it's Multibit (or Mycelium or blockchain.info)

Multibit should automatically estimate fees because it's too complicated for most users to get right.

I worry cases like this damage the reputation of bitcoin as a whole. I'd be happy to help test this or if I could help in any other way. (I think it's unproductive for me to write it because the time taken to learn the entire codebase would be long)

Now Multibit uses the bip37 p2p protocol connecting to other bitcoin nodes. Unfortunately they don't expose the `estimatefee` method so that can't be used. I think the easiest way to do this would be to query a centralized server that simply queries the `estimatefee` RPC call.

For example https://api.blockcypher.com/v1/btc/main or using the insight explorer API. Fees don't change very often so it's probably enough to query it at most once every few hours.

**Comment by gary-rowe** [comment]
MultiBit Classic is no longer being actively supported beyond critical security fixes. Please upgrade to MultiBit HD for a better chance of seeing this type of change.

You can read about upgrading here: https://multibit.org/en/help/hd0.3/how-to-upgrade-from-classic.html

Bear in mind that with 0.3.0 onwards there are no additional client fees, only miners fees.

Since this is unlikely to happen, I will close this issue.

**Comment by chris-belcher** [comment]
Ah so I have the wrong github repos.
